# Settings for the app
app:
  # HTML Title
  title: NY Rising
  # Header name
  name: Red Hook
  # Meta description that will show up in Google search results
  meta_description: _(NY Rising)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 40.67621
      lng: -74.01450
    zoom: 17
    minZoom: 16
    maxZoom: 18
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.150-NYRising-RH/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-2eefy58d/{z}/{x}/{y}.png

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  A:
    label: _(Economic)
    rules:
      - condition: '"{{location_type}}" === "A"'
        style:
          color: '#FF6F75'
          weight: 1
          fillOpacity: 0.5
        focus_style:
          color: '#FF6F75'
          weight: 1
          fillOpacity: 0.9
  B:
    label: _(Health and Social Services)
    rules:
      - condition: '"{{location_type}}" === "B"'
        style:
          color: '#0091FF'
          weight: 1
          fillOpacity: 0.5
        focus_style:
          color: '#0091FF'
          weight: 1
          fillOpacity: 0.9
  C:
    label: _(Housing)
    rules:
      - condition: '"{{location_type}}" === "C"'
        style:
          color: '#F9FF6A'
          weight: 1
          fillOpacity: 0.5
        focus_style:
          color: '#F9FF6A'
          weight: 1
          fillOpacity: 0.9
  D:
    label: _(Infrastructure Systems)
    rules:
      - condition: '"{{location_type}}" === "D"'
        style:
          color: '#CD95D7'
          weight: 1
          fillOpacity: 0.5
        focus_style:
          color: '#CD95D7'
          weight: 1
          fillOpacity: 0.9
  E:
    label: _(Natural and Cultural)
    rules:
      - condition: '"{{location_type}}" === "E"'
        style:
          color: '#67D666'
          weight: 1
          fillOpacity: 0.5
        focus_style:
          color: '#67D666'
          weight: 1
          fillOpacity: 0.9

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: false
  add_button_label: _(Add a missing asset)
  action_text: _(added)
  title: _(Describe this location)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - prompt: _(Location Name)
      type: text
      name: Name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
    - prompt: _(Asset type)
      type: select
      options:
        - label: _(Economic asset)
          value: Aadded
        - label: _(  Health and Social Services)
          value: Badded
        - label: _(Housing)
          value: Cadded
        - label: _(Infrastructure Systems)
          value: Dadded
        - label: _(Natural and Cultural)
          value: Eadded
      name: location_type
    - prompt: _(Describe the asset)
      type: textarea
      name: DESCRIPTIO
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your email, will not be shown on the map)
      type: text
      name: private-email
      attrs:
        - key: placeholder
          value: _(Email)
        - key: size
          value: 30
    - prompt: _(Nearest intersection to your home, will not be shown on the map)
      type: text
      name: private-address
      attrs:
        - key: placeholder
          value: _(Address)
        - key: size
          value: 30
    - type: hidden
      name: user-added
      attrs:
        - key: value
          value: 1
survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - type: hidden
      name: comment-type
      attrs:
        - key: value
          value: comment-type-correction
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true
